### ISSUE TITLE
Czy tak miało to wygladać?

### ISSUE THREAD

**Issue by jr-consulting** [jr-consulting/kodilla-js9.2-repository#1]
W tym zadaniu nie miałem pewności, czy te elementy html <span>span 1<span> i <p>1</p> miały być widoczne na stronie. W zadaniu w zasadzie nie ma o tym mowy. Z jednej strony następuje zmiana koloru na czerwony na podstawie funkcji, a z drugiej jednak to nie wyglada zbyt estetycznie.

**Comment by zdolny** [comment]
tak, mialy byc widoczne, dobrze to zrobiles, tylko numeracja powinna sie zwiekszac - brakuje Ci srednikow na koncach linii

**Comment by jr-consulting** [comment]
Nie do końca rozumiem, o jakie dokładnie poprawki chodzi, ponieważ w masterze:

- numeracja zwiększała się po naciśnięniu buttona;
- nic nie modyfikowałem w html;

Stworzyłem branch "wariantA", w którym inaczej ułożyłem numerację w html. Podejrzewam jednak, że to nie o to Ci chodziło.

Jeśli to nie ten efekt, to może chodzi o to żebym inkrementował wartość wartość index, zostawiajac w html pierwotne wpisy z "1" ?
